### 1. Health Check
GET http://localhost:1111/api/v1/health
Content-Type: application/json

### 1. Create Session
GET http://localhost:1111/api/v1/sessions/create?app=com.tencent.tmgp.sg
Content-Type: application/json

### 2. Get Session
POST http://localhost:1111/api/v1/sessions/get
Content-Type: application/json

{
    "game": "idle_weapon"
}